CUDA_VISIBLE_DEVICES=2 python main.py \
--train \
--use_fp16 \
--task webqa-finetune-full-data \
--use_wandb \
--model_name ofa-base \
--model_dir ./ofa-base \
--image_dir ../../utils/webqa_data/images/ \
--cache_dir ./cache/WebQA_full_data_cache/ \
--dataset_dir ./data/WebQA_full_data/ \
--gradient_accumulation_step 32 \
--train_file train.jsonl \
--val_file val.jsonl \
--num_epochs 15 \
--evaluation_steps 400 \
--question_max_length 50 \
--fact_max_length 100 \
--answer_max_length 1 \
--dev_batch_size 128 \
--train_batch_size 1 \
--real_batch_size 16 \
--choice_num 16 \
--learning_rate 1e-4 \
--warmup_steps 2000 \
--have_cached_dataset